version: 2

gitea_urls:
  api: https://git.trustservers.gr/api/v1
  download: https://git.trustservers.gr

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mymagicdump/
    env:
      - CGO_ENABLED=0
    goos:
      - linux 
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/trustservers-hosting/mymagicdump/internal/version.Version={{ .Tag }}'
      - -X 'github.com/trustservers-hosting/mymagicdump/internal/version.Commit={{ .ShortCommit }}'
      - -X 'github.com/trustservers-hosting/mymagicdump/internal/version.Date={{ .Date }}'

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"